version: 3.2.1-{branch}.{build}

environment:
  nodejs_version: "12.16.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build
  - npm pack

test_script:
  - npm run test-unit-with-coverage

after_test:
  - npm run publish-coverage

artifacts:
  - path: '*.tgz'
    name: NPM Package
